# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cd5de11e0439d4dfe67150489575b832"
name = "repofy-app"
handle = "repofy-app-2"
application_url = "https://arrivals-smart-lb-serve.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://arrivals-smart-lb-serve.trycloudflare.com/auth/callback", "https://arrivals-smart-lb-serve.trycloudflare.com/auth/shopify/callback", "https://arrivals-smart-lb-serve.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
